# Generated by Django 5.1.4 on 2025-03-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_oredr_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
