# Generated by Django 5.1.4 on 2025-04-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_summary',
        ),
    ]
