# Generated by Django 5.1.4 on 2025-04-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_summary_order_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_summary',
            name='order_item_id',
        ),
        migrations.AddField(
            model_name='order_summary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
