# Generated by Django 5.1.4 on 2025-04-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_cart_cartitemmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitemmodel',
            unique_together={('cart', 'cart_item')},
        ),
    ]
